version: '3'

services:
    web:
        build: .
        command: ['gunicorn', '--bind', '0.0.0.0:5000', 'app:create_app()']
        volumes:
            - .:/app
        ports:
            - '5000:5000'
        environment:
            FLASK_ENV: 'development'
            FLASK_DEBUG: 'True'
            SECRET_KEY: 'some_secret_key_here_for_testing12321!@'
            DATABASE_URL: 'postgresql://postgres:postgres@db:5432/pet_overload'
            SQLALCHEMY_TRACK_MODIFICATIONS: 'False'
    db:
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: pet_overload
        ports:
            - '5432:5432'
